### ISSUE TITLE
tests fail inconsistently

### ISSUE THREAD

**Issue by afeld** [18F/hub#209]
Running `./go ci_build` seems to fail after the third(?) time it runs... `rm .jekyll-metadata` seems to fix the issue. Very possible this is a Jekyll 3 bug...need to investigate further.

```
  Liquid Exception: Liquid syntax error: Unexpected character \ in "{{ location.projects.size | pluralize: \"project\" }}" in api/v1/pages.json
/Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/lexer.rb:42:in `tokenize': Liquid syntax error: Unexpected character \ in "{{ location.projects.size | pluralize: \"project\" }}" (Liquid::SyntaxError)
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/parser.rb:5:in `initialize'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/variable.rb:64:in `new'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/variable.rb:64:in `strict_parse'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/parser_switching.rb:21:in `strict_parse_with_error_context'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/parser_switching.rb:5:in `parse_with_selected_parser'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/variable.rb:25:in `initialize'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/block.rb:102:in `new'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/block.rb:102:in `block in create_variable'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/block.rb:100:in `scan'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/block.rb:100:in `create_variable'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/block.rb:44:in `parse'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/tag.rb:10:in `parse'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/block.rb:31:in `parse'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/tag.rb:10:in `parse'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/block.rb:31:in `parse'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/tag.rb:10:in `parse'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/document.rb:5:in `parse'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/template.rb:122:in `parse'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/liquid-3.0.1/lib/liquid/template.rb:108:in `parse'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.0.beta2/lib/jekyll/convertible.rb:106:in `render_liquid'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.0.beta2/lib/jekyll/convertible.rb:239:in `do_layout'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.0.beta2/lib/jekyll/page.rb:118:in `render'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/jekyll_pages_api-0.1.1/lib/jekyll_pages_api/generator.rb:35:in `page'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/jekyll_pages_api-0.1.1/lib/jekyll_pages_api/generator.rb:41:in `generate'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/jekyll_pages_api-0.1.1/lib/jekyll/site.rb:14:in `after_render'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/jekyll_pages_api-0.1.1/lib/jekyll/site.rb:10:in `render'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.0.beta2/lib/jekyll/site.rb:55:in `process'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.0.beta2/lib/jekyll/command.rb:28:in `process_site'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.0.beta2/lib/jekyll/commands/build.rb:59:in `build'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.0.beta2/lib/jekyll/commands/build.rb:34:in `process'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.0.beta2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.0.beta2/bin/jekyll:17:in `<top (required)>'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/bin/jekyll:23:in `load'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/bin/jekyll:23:in `<main>'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/aidanfeldman/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

***
Site failed to build for pages_api_test
***
```

**Comment by mbland** [comment]
@afeld So `.jekyll-metadata` is just a text file. That means we can diff it. Watch this:
```shell
$ rm .jekyll-metadata
$ bundle exec jekyll build
  ...
$ cp .jekyll-metadata .jekyll-metadata-0
$ bundle exec jekyll build
  ...
$ cp .jekyll-metadata .jekyll-metadata-1
$ bundle exec jekyll build
```
You get the idea. Do this until you create `.jekyll-metadata-5`. And after that:
```shell
$ bundle exec jekyll build
Configuration file: .../hub/_config.yml
            Source: .../hub
       Destination: .../hub/_site
 Incremental build: enabled
      Generating... 
  Liquid Exception: Liquid syntax error: Unexpected character \ in "{{ location.projects.size | pluralize: \"project\" }}" in api/v1/pages.json
jekyll 3.0.0.beta2 | Error:  Liquid syntax error: Unexpected character \ in "{{ location.projects.size | pluralize: \"project\" }}

$ cp .jekyll-metadata .jekyll-metadata-6
$ diff .jekyll-metadata-{5,6}
  [no diff]
```
Now dig this:
```shell
$ diff .jekyll-metadata-{0,1}
1730a1731,1748
> "hub/_layouts/news.html":
>   mtime: 2015-03-06 12:27:28.000000000 -05:00
>   deps: []
> "hub/_includes/head.html":
>   mtime: 2015-03-06 12:27:28.000000000 -05:00
>   deps: []
> "hub/_layouts/q-and-a.html":
>   mtime: 2015-03-06 12:27:28.000000000 -05:00
>   deps: []
> "hub/_includes/twitter_favorites.html":
>   mtime: 2015-03-06 12:27:28.000000000 -05:00
>   deps: []
> "hub/_includes/team_members.html":
>   mtime: 2015-03-06 12:27:28.000000000 -05:00
>   deps: []
> "hub/_includes/team_members_short.html":
>   mtime: 2015-03-06 12:27:28.000000000 -05:00
>   deps: []

$ diff .jekyll-metadata-{1,2}
1748a1749,1751
> "hub/_includes/ascii.html":
>   mtime: 2015-03-06 12:27:28.000000000 -05:00
>   deps: []

$ diff .jekyll-metadata-{2,3}
1751a1752,1757
> "hub/_includes/nav-main.html":
>   mtime: 2015-03-06 12:27:28.000000000 -05:00
>   deps: []
> "hub/_includes/footer.html":
>   mtime: 2015-03-06 12:27:28.000000000 -05:00
>   deps: []

$ diff .jekyll-metadata-{3,4}
1757a1758,1763
> "hub/_includes/edit_link.html":
>   mtime: 2015-03-06 12:27:28.000000000 -05:00
>   deps: []
> "hub/_includes/scripts.html":
>   mtime: 2015-03-06 12:27:28.000000000 -05:00
>   deps: []

$ diff .jekyll-metadata-{4,5}
1763a1764,1769
> "hub/_layouts/bare.html":
>   mtime: 2015-03-06 12:27:28.000000000 -05:00
>   deps: []
> "hub/_layouts/default.html":
>   mtime: 2015-03-06 12:27:28.000000000 -05:00
>   deps: []
```
Delete the `bare.html` entry, and `bundle exec jekyll build` builds successfully, adding `bare.html` to the bottom of `.jekyll-metadata`. Then the next `bundle exec jekyll build` fails.

Copying `.jekyll-metadata-0` to `.jekyll-metadata` and adding the `bare.html` results in a successful `bundle exec jekyll build`. Gotta run now, but will try to keep rebuilding until it fails again, unless you beat me to it or figure out the problem before then.

I don't know yet what any of this means, but them's the data.

**Comment by parkr** [comment]
From a CI perspective, I'd probably always run `jekyll build --full-rebuild` :)

**Comment by mbland** [comment]
Hmm. Files from `_layouts` and `_includes` only start appearing as top-level YAML objects in `.jekyll-metadata` from the second build on (i.e. they don't appear in the `.jekyll-metadata-0` file from the above example, but do appear in the rest).

**Comment by afeld** [comment]
Closing as stale.
